# Generated by Django 3.1 on 2020-08-14 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20200813_0627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='directors',
            new_name='director',
        ),
    ]
